### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by calmh** [kardianos/vendor#5] opened 2015-04-20 03:01 UTC
This is on a clean (non-vendored) checkout, where I've just `rm -rf Godeps` to get those out of the way..

```
jb@syno:~/src/github.com/syncthing/syncthing (vendor) $ vendor init
jb@syno:~/src/github.com/syncthing/syncthing (vendor) $ vendor add -status ext
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6847f]

goroutine 1 [running]:
github.com/kardianos/vendor/rewrite.addUpdateImportPath(0x208480ece, 0x28, 0x237a00, 0x0, 0x0)
	/Users/jb/src/github.com/kardianos/vendor/rewrite/command.go:345 +0x181f
github.com/kardianos/vendor/rewrite.CmdAdd(0x208480ece, 0x28, 0x0, 0x0)
	/Users/jb/src/github.com/kardianos/vendor/rewrite/command.go:195 +0x50
main.main()
	/Users/jb/src/github.com/kardianos/vendor/main.go:137 +0x9bf
[2]
jb@syno:~/src/github.com/syncthing/syncthing (vendor) $ 
```

(2260c62)

**Comment by kardianos** [comment] 2015-04-20 03:47
The cause of the panic should be fixed with https://github.com/kardianos/vendor/commit/ebb968f2818ffe62010968c2f242db8119febbf2 .

However, inspecting the behavior leads me to believe there is another underlying bug with "vendor list" command correctness. I'll open another issue to track that. behavior.

Thanks again.

**Closed by kardianos** 2015-04-20 03:47 UTC

**Comment by kardianos** [comment] 2015-04-20 03:49
Opened https://github.com/kardianos/vendor/issues/6 for discovered issue.

**Comment by calmh** [comment] 2015-04-20 05:01
:+1: Looks better now :)

**Comment by kardianos** [comment] 2015-04-20 14:12
@calmh both issues have now been resolved.
