### ISSUE TITLE
Merges internal namespaces

### ISSUE THREAD

**Issue by calmh** [kardianos/vendor#2] opened 2015-04-17 06:00 UTC
Perhaps this is according the the spec (I admit to not fully reading it and just going by how I think it should work ;), but to me this is unexpected:

```json
		{
			"Vendor": "golang.org/x/text/unicode/norm",
			"Local": "github.com/syncthing/syncthing/internal/golang.org/x/text/unicode/norm",
			"Version": "2076e9cab4147459c82bc81169e46c139d358547",
			"VersionTime": "2015-03-17T19:07:45+09:00"
		},
		{
			"Vendor": "golang.org/x/text/internal/triegen",
			"Local": "github.com/syncthing/syncthing/internal/triegen",
			"Version": "2076e9cab4147459c82bc81169e46c139d358547",
			"VersionTime": "2015-03-17T19:07:45+09:00"
		},
		{
			"Vendor": "golang.org/x/text/internal/ucd",
			"Local": "github.com/syncthing/syncthing/internal/ucd",
			"Version": "2076e9cab4147459c82bc81169e46c139d358547",
			"VersionTime": "2015-03-17T19:07:45+09:00"
		}
```

That is, `golang.org/x/text/unicode/norm` is located where I expect it, but `golang.org/x/text/internal/triegen` and `.../ucd` gets dropped directly in `github.com/syncthing/syncthing/internal`?

**Comment by kardianos** [comment] 2015-04-17 14:15
That's an issue. It needs to be more exact when determining the final path.
I'll look into. Thanks.

**Comment by kardianos** [comment] 2015-04-17 16:24
@calmh Thanks. I've looked into this some more and I can confirm that this is an issue caused from not looking for and inspecting the vendor file of the package being imported. Because of that it incorrectly assumes it should pop the vendor internal package to a top level package.

**Comment by kardianos** [comment] 2015-04-17 16:41
@calmh This should be fixed on: https://github.com/kardianos/vendor/commit/2b0b5efac01334b3972646bee5f433f0cea725f1
. Thanks.

**Closed by kardianos** 2015-04-17 16:41 UTC

**Comment by calmh** [comment] 2015-04-19 08:33
:+1:
